# Generated by Django 3.1.1 on 2020-12-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('symptom1', models.CharField(max_length=30)),
                ('symptom2', models.CharField(blank=True, max_length=30)),
                ('symptom3', models.CharField(blank=True, max_length=30)),
                ('symptom4', models.CharField(blank=True, max_length=30)),
                ('symptom5', models.CharField(blank=True, max_length=30)),
                ('disease', models.CharField(max_length=30)),
                ('consultDoctor', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Predict',
        ),
    ]
